name: Generate PDF Slides

on:
  push:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Start live-server
        run: |
          nohup npx live-server docs --port=8080 --quiet --no-browser > live-server.log 2>&1 &
          echo "Started live-server, waiting for it to initialize..."
          sleep 15

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Generate PDF with DeckTape
        run: |
          docker run --rm -v ${{ github.workspace }}:/slides astefanutti/decktape remark http://127.0.0.1:8080/ slides.pdf

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: slides-pdf
          path: slides.pdf
